name: build-native

on: workflow_dispatch

env:
  MAKE_PARALLELISM: -j2
  TEXBIN: ctangle otangle tangle tangleboot ctangleboot tie web2c/fixwrites web2c/makecpool web2c/splitup web2c/web2c

jobs:

  build-native:
    runs-on: ubuntu-20.04
    container: alpine:3.17
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils cmake git xz wget perl gperf p7zip python3 strace && ln -sf python3 /usr/bin/python

      - name: Install Hub
        run:  apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing hub github-cli

      - uses: actions/checkout@v2
      
      - name: Clone TexLive and dependencies
        run:  make source/texlive.downloaded build/versions.txt

      - name: Build native busytex
        env:
            MAKEFLAGS: ${{env.MAKE_PARALLELISM}}
        run:  make native
      
      - name: Smoke native
        run:  make test

      - name: Test native 
        run: |
            make tds-basic
            make dist-native
            sh example/example.sh

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            chown $(whoami) -R .
            #hub release create -m "Native assets" -a build/versions.txt -a build/native/fonts.conf -a build/native/busytex -a build/native/texlive/texk/web2c/busyweb2c -a build/native/busytex.tar $(printf -- "-a build/native/texlive/texk/web2c/%s " $TEXBIN) build_${{github.sha}}
             gh release create -t build_${{github.sha}} --notes native_assets build/versions.txt build/native/fonts.conf build/native/busytex build/native/texlive/texk/web2c/busyweb2c build/native/busytex.tar $(printf "build/native/texlive/texk/web2c/%s " $TEXBIN)
