name: build-wasm

on: 
  workflow_dispatch:
    inputs:
      busytexreleasetag:
        description: 'busytex release tag'
        required: false
        default: 'build_70e692454a6ed21372a35783f8a11c0c133726d7'

env:
  BUSYTEX_RELEASES_URL: https://github.com/busytex/busytex/releases
  UBUNTUPACKAGES: texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-science texlive-fonts-recommended
  EMSCRIPTEN_VERSION: 2.0.30
  MAKE_PARALLELISM: -j2

jobs:

  build-wasm:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Prerequisites
        run:  sudo apt-get install -y gperf p7zip-full strace icu-devtools

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{env.EMSCRIPTEN_VERSION}}

      - uses: actions/checkout@v2

      - name: Download native binaries
        run:  make URLRELEASE=$BUSYTEX_RELEASES_URL/download/${{ github.event.inputs.busytexreleasetag }} download-native
      
      - name: Clone/patch TexLive and dependencies
        run:  make source/texlive.downloaded build/versions.txt

      #- name: Build native busytex
      #  env:
      #      MAKEFLAGS: ${{env.MAKE_PARALLELISM}}
      #  run: |
      #      make native
      #      make test
      
      - name: Replace native busytex
        run: make replace-native
      
      - name: Build wasm busytex
        run: make wasm
        #env:
        #    MAKEFLAGS: ${{env.MAKE_PARALLELISM}}

      #- name: Download TexLive Full
      #  run:  make source/texmfrepo.txt

      #- name: Install TexLive
      #  run: |
      #      make tds-basic
      #      make tds-full

#      - name: Archive native artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: native_build
#          path: |
#            build/texlive-basic/
#            build/native/busytex

      #- name: Create Basic package
      #  run: make build/wasm/texlive-basic.js
      #
      #- name: Create Ubuntu packages
      #  run:  make $(printf "build/wasm/ubuntu-%s.js " $UBUNTUPACKAGES) -e TEXMF_FULL=build/texlive-full 

      #- name: Create Release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #      make dist-wasm
      #      hub release create -m "Wasm assets" -a busytex_pipeline.js -a busytex_worker.js -a build/versions.txt -a build/wasm/busytex.js -a build/wasm/busytex.wasm   -a source/texmfrepo.txt -a build/texlive-basic.txt -a build/texlive-full.txt -a build/wasm/texlive-basic.js -a build/wasm/texlive-basic.data $(printf -- "-a build/wasm/ubuntu-%s.js " $UBUNTUPACKAGES) $(printf -- "-a build/wasm/ubuntu-%s.data " $UBUNTUPACKAGES) $(printf -- "-a build/wasm/ubuntu-%s.skip.txt " $UBUNTUPACKAGES) $(printf -- "-a build/wasm/ubuntu-%s.good.txt " $UBUNTUPACKAGES) build_${{github.sha}}
