name: build

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: 2.0.5
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Install Prerequisites
        run: sudo apt-get install -y gperf
        
      - name: Clone/patch TexLive and dependencies
        run: make texlive 

      - name: Build native busytex
        run: make native build/native/fonts.conf
        env:
            MAKEFLAGS: -j2
        
      - name: Install TexLive scheme-basic
        run: make tds-basic
      
      - name: Test native busytex with a xetex+bibtex8+xetex+xetex+xdvidpfmx pipeline
        run: |
            make dist-native
            bash example/example.sh

      - name: Build wasm busytex
        run: |
            echo FIN && exit 1
            make wasm
            make build/wasm/fonts.conf
            make build/wasm/texlive-basic.js
            make dist-wasm
        env:
            MAKEFLAGS: -j2
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub release create -m "Build assets" -a busytex_pipeline.js -a busytex_worker.js -a build/format-basic/xelatex.fmt -a build/wasm/texlive-basic.js -a build/wasm/texlive-basic.data -a build/wasm/busytex.js -a build/wasm/busytex.wasm -a build/native/busytex -a build/native/fonts.conf build_${{github.sha}}
