name: build-native

on: workflow_dispatch

env:
  MAKE_PARALLELISM: -j2
  ICUBIN: icupkg pkgdata
  TEXBIN: ctangle otangle tangle tangleboot ctangleboot tie web2c/fixwrites web2c/makecpool web2c/splitup web2c/web2c
  FREETYPEBIN: apinames

jobs:

  build-native:
    runs-on: ubuntu-20.04
    container: alpine:3.14
    steps:
      - name: Install Prerequisites
        run:  apk add --update --no-cache libnsl libnsl-dev build-base coreutils cmake git xz wget perl gperf p7zip python3 strace && ln -sf python3 /usr/bin/python

      - name: Install Hub
        run:  apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing hub 

      - uses: actions/checkout@v2
      
      - name: Clone/patch TexLive and dependencies
        run:  make texlive build/versions.txt

      - name: Build native busytex
        env:
            MAKEFLAGS: ${{env.MAKE_PARALLELISM}}
        run:  make native
      
      - name: Smoke native
        run:  make test

      - name: Test native 
        run: |
            make tds-basic
            make dist-native
            MYOLDPWD="$PWD"
            echo PWD="$PWD"
            sh example/example.sh
            echo PWD="$PWD"
            cd "$MYOLDPWD"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo PWD="$PWD"
            ls
            hub release create -m "Native assets" -a build/versions.txt -a build/native/fonts.conf -a build/native/busytex -a build/native/busytex.tar  $(printf -- "-a build/native/texlive/libs/freetype2/ft-build/%s " $FREETYPEBIN) $(printf -- "-a build/native/texlive/libs/icu/icu-build/bin/%s " $ICUBIN) $(printf -- "-a build/native/texlive/texk/web2c/%s " $TEXBIN) build_${{github.sha}}
