# https://www.freecodecamp.org/news/a-lightweight-tool-agnostic-ci-cd-flow-with-github-actions/
# https://github.com/actions/upload-release-asset
# https://github.com/actions/upload-release-asset/issues/28

name: make

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Prerequisites
        run: sudo apt-get install -y gperf
        
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Clone/patch TexLive and dependencies
        run: make texlive 

      - name: Build native busytex
        run: make native build/native/fonts.conf
        env:
            MAKEFLAGS: -j2
        
      - name: Install TexLive scheme-basic
        run: make tds-basic
      
      - name: Test native busytex with a xetex+bibtex8+xetex+xetex+xdvidpfmx pipeline
        run: |
            make dist-native
            bash example/example.sh

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: 2.0.5

      - name: Build wasm busytex
        run: |
            make wasm
            make build/wasm/fonts.conf
            make build/wasm/texlive-basic.js
            make dist-wasm
        env:
            MAKEFLAGS: -j2
      
      - name: Archive native busytex test
        uses: actions/upload-artifact@v2
        with:
          name: dist_native
          path: |
              dist-native
              example/example.pdf
      
      - name: Archive wasm busytex dist
        uses: actions/upload-artifact@v2
        #if: ${{ always() }}
        with:
          name: dist_wasm
          path: dist-wasm
