name: install-tl

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Prerequisites
        run: sudo apt-get install -y gperf p7zip-full
        
      - name: Download TexLive full
        run: |
            mkdir -p source/texmfrepo build/texlive-basic
            wget -P source https://ftp.tu-chemnitz.de/pub/tug/historic/systems/texlive/2020/texlive2020-20200406.iso
	        7z e source/texlive2020-20200406.iso -aoa -osource/texmfrepo || true
            echo selected_scheme scheme-basic > build/texlive.profile
            echo TEXDIR $PWD/build/texlive-basic >> build/texlive.profile
            echo TEXMFLOCAL $PWD/build/texlive-basic/texmf-local >> build/texlive.profile
            echo TEXMFSYSVAR $PWD/build/texlive-basic/texmf-var >> build/texlive.profile
            echo TEXMFSYSCONFIG $PWD/build/texlive-basic/texmf-config >> build/texlive.profile
            chmod +x ./source/texmfrepo/install-tl
            TEXLIVE_INSTALL_NO_RESUME=1 strace -ff ./source/texmfrepo/install-tl --repository source/texmfrepo --profile build/texlive.profile

