# https://www.freecodecamp.org/news/a-lightweight-tool-agnostic-ci-cd-flow-with-github-actions/
# https://github.com/actions/upload-release-asset

name: make

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Install Prerequisites
        run: sudo apt-get install -y gperf
      
      - name: Install TexLive scheme-basic
        run: make tds-basic
      
      - name: Clone/patch TexLive and dependencies
        run: make texlive 

      - name: Build native busytex
        run: |
            make native 
            make tds-native
            make dist-native
      
      - name: Test native busytex with a xetex+bibtex8+xetex+xetex+xdvidpfmx pipeline
        run: bash example/example.sh

      - name: Archive native busytex test
        uses: actions/upload-artifact@v2
        with:
          name: example_example.pdf
          path: example/example.pdf
 
#      - name: Build wasm busytex
#        run: make wasm tds-wasm

