# https://www.freecodecamp.org/news/a-lightweight-tool-agnostic-ci-cd-flow-with-github-actions/
# https://github.com/actions/upload-release-asset
# https://github.com/actions/upload-release-asset/issues/28

name: ubuntupackages
env:
  UBUNTUPACKAGES: texlive-latex-base texlive-latex-extra texlive-latex-recommended

on: workflow_dispatch

jobs:

  ubuntu-packages-wasm:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: 2.0.5
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Install TexLive
        run: make build/install-tl/install-tl build/texlive-basic/texmf-dist

      - name: Recreate Ubuntu packages
        run: |
          printenv
          make -e TEXMF_FULL=build/texlive-basic $(printf "build/wasm/ubuntu-%s.js " $UBUNTUPACKAGES)

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv
          tagname=$(basename ${{ github.ref }})
          hub release create $(printf -- "-a build/wasm/ubuntu-%s.js -a build/wasm/ubuntu-%s.data " $UBUNTUPACKAGES) -m $tagname $tagname
          
