name: ubuntupackages
env:
  UBUNTUPACKAGES: texlive-latex-base texlive-latex-extra texlive-latex-recommended

on: workflow_dispatch

jobs:

  ubuntu-packages-wasm:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: 2.0.5
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      
      - name: Install TexLive
        run: make build/install-tl/install-tl build/texlive-full/texmf-dist

      - name: Recreate Ubuntu packages
        run: make $(printf "build/wasm/ubuntu-%s.js " $UBUNTUPACKAGES) -e TEXMF_FULL=build/texlive-full 

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub release create -m "Ubuntu packages assets" $(printf -- "-a build/wasm/ubuntu-%s.js " $UBUNTUPACKAGES) $(printf -- "-a build/wasm/ubuntu-%s.data " $UBUNTUPACKAGES) $(printf -- "-a build/wasm/ubuntu-%s.skipped.txt " $UBUNTUPACKAGES) ubuntupackages_${{github.sha}}
